openapi: 3.1.0
info:
  title: Polymorphic API Example
  version: 1.0.0
paths:
  /pets:
    get:
      summary: Get pets
      responses:
        '200':
          description: List of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      oneOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
      discriminator:
        propertyName: petType
        mapping:
          cat: '#/components/schemas/Cat'
          dog: '#/components/schemas/Dog'
    Cat:
      type: object
      required:
        - petType
        - hunts
      properties:
        petType:
          type: string
          const: cat
        hunts:
          type: boolean
        breed:
          type:
            - string
            - 'null'
    Dog:
      type: object
      required:
        - petType
        - barkVolume
      properties:
        petType:
          type: string
          const: dog
        barkVolume:
          type: integer
          minimum: 1
          maximum: 10
        breed:
          type:
            - string
            - 'null'
