name: Release All SDKs

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of all SDKs that you would like to release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Fern
        run: npm install -g fern-api

      - name: Generate All SDKs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
        run: |
          fern generate --group all-sdks --api edgeworkers --log-level debug 