name: Release Ruby SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the Ruby SDK that you would like to release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Fern
        run: npm install -g fern-api

      - name: Generate Ruby SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
        run: |
          fern generate --group ruby-sdk --version ${{ inputs.version }} --api edgeworkers --log-level debug 